name: Debug

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Show properties
        run: echo ${{ github }}
