name: Debug

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print commiter name
        run: echo "The commiter name is ${{ github.actor }}"

      - name: Print owner name
        run: echo "The owner name is ${{ github.repository_owner }}"

  restrict:
    runs-on: ubuntu-latest
    # A job can expose output to another job
    outputs:
      # The value of committer is set (from env.GIT...) after the job is done
      committer: ${{ env.GIT_COMMIT_COMMITTER_NAME }}
    steps:
      - uses: actions/checkout@v2
      # This is the action that sets the value of env.GIT_COMMIT_COMMITTER_NAME
      - uses: rlespinasse/git-commit-data-action@v1.5.0

  release:
    # needs creates a dependency between jobs: this job won't run until
    # the restrict job is complete
    needs: restrict
    runs-on: ubuntu-latest
    # a job can access the outputs of a job it depends on through needs
    if: needs.restrict.outputs.committer == 'weblate'
    steps:
      - name: Get current date
        id: date
        run: TZ=Asia/Tokyo echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
