name: build and push image (Debian version)

on:
  push:
    branches:
      - "master"
    paths:
      - Dockerfile.debian
      - .github/workflows/docker-build-debian.yml
      - renew*.py
      - requirements.txt

env:
  IMAGE_NAME: "simaofsilva/noip-renewer"
  PIP_VERSION: "23.3.2" # renovate: datasource=pypi depName=pip versioning=pep440
  GECKODRIVER_VERSION: "v0.34.0" # renovate: datasource=github-tags depName=mozilla/geckodriver

jobs:
  build-debian:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Get commit short hash
        id: short_digest
        run: echo "shortsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build image for tests
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}:test-debian
          file: Dockerfile.debian
          build-args: |
            PIP_VERSION=${{ env.PIP_VERSION }}
            GECKODRIVER_VERSION=${{ env.GECKODRIVER_VERSION }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: ${{ env.IMAGE_NAME }}:test-debian
          format: "sarif"
          output: "trivy-debian-image-scan.sarif"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "MEDIUM,CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3.23.0
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: trivy-debian-image-scan.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: debian-image-scan

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build for ARM v7 (caching)
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/arm/v7
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.short_digest.outputs.shortsha }}-armv7
          file: Dockerfile.debian
          build-args: |
            PIP_VERSION=${{ env.PIP_VERSION }}
            GECKODRIVER_VERSION=${{ env.GECKODRIVER_VERSION }}

      - name: Build and push all to Docker Hub
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/arm/v7,linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.short_digest.outputs.shortsha }}-debian
            ${{ env.IMAGE_NAME }}:debian
          file: Dockerfile.debian
          build-args: |
            PIP_VERSION=${{ env.PIP_VERSION }}
            GECKODRIVER_VERSION=${{ env.GECKODRIVER_VERSION }}

  validate-Dockerfile:
    uses: ./.github/workflows/hadolint.yml
    with:
      filename: Dockerfile.debian
