name: build and push image (Debian version)

on:
  push:
    branches:
      - "master"

jobs:
  build-debian:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      variant: debian
      dockerfile: Dockerfile.debian
      platforms: linux/arm/v7,linux/amd64,linux/arm64/v8
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
