name: Isort

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Check isort compliance
        uses: isort/isort-action@v1.1.0
        with:
          sort-paths: renew.py
