name: build and scan image (Alpine version)

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - Dockerfile
      - renew*.py
      - requirements.txt
      - .github/workflows/pr-alpine.yml
      - .github/workflows/pr.yml

jobs:
  build-alpine:
    uses: ./.github/workflows/pr.yml
    with:
      variant: alpine
      dockerfile: Dockerfile
