name: build and scan image (Alpine version)

on:
  push:
    branches-ignore:
      - "master"

env:
  IMAGE_NAME: "simaofsilva/noip-renewer"
  PIP_VERSION: "23.3.2" # renovate: datasource=pypi depName=pip versioning=pep440

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build image for tests
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}:test-alpine
          file: Dockerfile
          build-args: |
            PIP_VERSION=${{ env.PIP_VERSION }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:test-alpine
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "MEDIUM,HIGH,CRITICAL"
          skip-files: "/usr/bin/geckodriver,/usr/local/bin/geckodriver,/usr/lib/librav1e.so.0.6.6"

      # On hold until https://github.com/aquasecurity/trivy-action/issues/228 is fixed
      # - name: Upload Trivy scan results to GitHub Security
      #   uses: github/codeql-action/upload-sarif@v2
      #   if: always()
      #   with:
      #     # Path to SARIF file relative to the root of the repository
      #     sarif_file: trivy-alpine-image-scan.sarif
      #     # Optional category for the results
      #     # Used to differentiate multiple results for one commit
      #     category: alpine-image-scan

  validate-Dockerfile:
    uses: ./.github/workflows/hadolint.yml
    with:
      filename: Dockerfile
