name: build and scan image (Alpine version)

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build-alpine:
    uses: ./.github/workflows/pr.yml
    with:
      variant: alpine
      dockerfile: Dockerfile
