name: build and scan image (Debian version)

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - Dockerfile.debian
      - renew*.py
      - requirements.txt
      - .github/workflows/pr-debian.yml

jobs:
  build-debian:
    uses: ./.github/workflows/pr.yml
    with:
      variant: debian
      dockerfile: Dockerfile.debian
