name: build and scan image (Debian version)

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-debian:
    uses: ./.github/workflows/pr.yml
    with:
      variant: debian
      dockerfile: Dockerfile.debian
